### ISSUE TITLE
https for the site?

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/stagehand#355]
It is hosted on Firebase? Could it be?

That'd make https easy...

**Comment by kwalrath** [comment]
It's hosted with gh-pages, but I have no objection to hosting it on Firebase (if someone else does the work :).

**Comment by kevmoo** [comment]
Ha! K.

**Comment by kevmoo** [comment]
We killed off the stagehand.pub site – so this issue doesn't apply...

Thanks for asking!
