### ISSUE TITLE
Travis: run dartfmt over templates

### ISSUE THREAD

**Issue by chalin** [dart-lang/stagehand#399]
@devoncarew @kevmoo - any reason not to run dartfmt over the templates?

**Comment by devoncarew** [comment]
+1 - having the templates formatted sounds great

**Comment by kwalrath** [comment]
My only quibble is that if code from a template is featured in documentation, we might want to specify a <80 line length, to avoid line breaks. (dartfmt can handle that, I'm just not sure where we need it.)
