### ISSUE TITLE
web-angular: use a `<reorder-list>` once issue is fixed

### ISSUE THREAD

**Issue by chalin** [dart-lang/stagehand#405]
Blocking: https://github.com/dart-lang/angular_components/issues/19

From https://github.com/google/stagehand/pull/401#issuecomment-300207673:
> Here is the template fragment to reinstate once that ACX issue is fixed:
```html
<div *ngIf="items.isNotEmpty">
  <p>Drag-and-drop items to reorder them.</p>
  <ul>
    <reorder-list (reorder)="onReorder($event)">
      <li *ngFor="let item of items; let i=index" reorderItem>
        <material-checkbox #done materialTooltip="Mark item as done">
        </material-checkbox>
        <span [class.done]="done.checked">{{item}}</span>
        <material-fab mini (trigger)="remove(i)">
          <glyph icon="delete"></glyph>
        </material-fab>
      </li>
    </reorder-list>
  </ul>
</div>
```

**Comment by kwalrath** [comment]
Closing because it looks like reorder-list won't be fixed: dart-lang/angular_components#184

**Comment by chalin** [comment]
Ok, though I was hoping that https://github.com/dart-lang/angular_components/issues/184 could be tagged as "help wanted".

**Comment by kwalrath** [comment]
Apparently, reports of reorder-lists's death were exaggerated. It looks like we'll keep it but mark it as unsupported (and, I hope, solicit fixes).

**Comment by chalin** [comment]
Great!

**Comment by kwalrath** [comment]
We probably shouldn't feature a component that isn't fully supported, so I'm going to close this.
