### ISSUE TITLE
chore(travis): split app tests from the rest of the build

### ISSUE THREAD

**Issue by chalin** [dart-lang/stagehand#424]
@kevmoo's request from https://github.com/google/stagehand/pull/423#issuecomment-305897691:
> I'd rather split out the matrix so the angular test stuff is it's own test.
Then we can mark *that* as failing.

cc @kwalrath

**Comment by chalin** [comment]
@kevmoo - are you sure we want to split off the testing? Of what use is an app template if the tests fail to run over it?

**Comment by kevmoo** [comment]
We should chat next week. Split – set up an environment variable so we have 4 test groups instead of two.

Know what I mean?
