### ISSUE TITLE
Seems that stagehand 1.1.6 has been released but is not tagged

### ISSUE THREAD

**Issue by agamdua** [dart-lang/stagehand#449]
There is no git tag for version 1.1.6 even though it has been pushed to the public pub repository.

Previous versions do seem to have tags.

 [This](https://github.com/dart-lang/stagehand/blob/master/CHANGELOG.md#116) leads me to believe there is a CI job or a script that used to do this, it may be pointing to the old repository that used to be under github.com/google.

**Comment by agamdua** [comment]
I did a cursory check under `tools/` and couldn't find anything, if there is something I missed that I can update, feel free to point me in the right direction.

**Comment by agamdua** [comment]
Correction - it is indeed tagged. The convention is different. The other tags are prefixed with `v`, this one is not. Github's UI made this difficult to see, I did not previously think to scroll all the way to the bottom since I saw a convention there. Would it be worth adhering to convention? This is up to the project contributors obviously, it may be that this removal of the prefix was deliberate.

https://github.com/dart-lang/stagehand/tree/1.1.6

**Comment by kwalrath** [comment]
Thanks for looking into this. We do indeed have a convention to use "v" (as mentioned in [Pushing a new version](https://github.com/dart-lang/stagehand/wiki/Pushing-a-new-version)), and I think that this exception was just an accident.

I'm closing this and will deal with this "v" thing off thread. ;)

cc @kevmoo

**Comment by agamdua** [comment]
Did not notice the wiki before - 👍
