### ISSUE TITLE
web-angular exception: 'package:angular/src/di/injector/reflective.dart'

### ISSUE THREAD

**Issue by gchumillas** [dart-lang/stagehand#458]
After creating a new web-angular project and running it into Dartium, I get the following error:
```error
Exception: 'package:angular/src/di/injector/reflective.dart': error: line 259 pos 19: ')' expected
      assert(false, 'Unsupported: ${item.runtimeType}');
```

**Steps to reproduce the problem**:
```bash
$ stagehand web-angular
$ pub get
$ pub serve --web-compiler=dartdevc
```
And then execute Dartium and open `localhost:8080`

**Additional information**:
```
Ubuntu 16.04
Dart VM version: 1.24.2 (Thu Jun 22 15:42:21 2017) on "linux_x64"
Pub 1.24.2
```

**Comment by matanlurey** [comment]
Dartdevc needs to be run in Chrome, not Dartium.

**Comment by gchumillas** [comment]
Many thanks. After a long trip, I realized that everything has changed. Even the apocryphal version 2.0 of Angular2 had disappeared.
