### ISSUE TITLE
Please release the 2-dev branch to pub

### ISSUE THREAD

**Issue by rwrozelle** [dart-lang/stagehand#470]
Please release the 2-dev branch to pub similar to how other packages are providing 2 versions to make it easier to work with both production and Dart 2.0 development.  See https://pub.dartlang.org/packages/angular for an example of the pub providing both versions.

Thanks,
Bob

**Comment by kwalrath** [comment]
@chalin could you update the 2-dev branch so it's ready to publish?

**Comment by chalin** [comment]
@kwalrath - while #471 updated the 2-dev branch, note that the `web-angular` template switched to using the "mock" `pageloader`. We might not want to publish quite yet.

**Comment by kwalrath** [comment]
When do you think we'd want to publish? When the new pageloader is out? (That could be a while.)

**Comment by chalin** [comment]
Maybe at least await for Dart 2 Beta 2/3, and Angular 5?

I question how useful this will be given that WebStorm doesn't yet officially support Dart 2 / Angular 5.

**Comment by kevmoo** [comment]
Let's wait until an SDK is out w/ pub build/serve removed - https://github.com/dart-lang/sdk/issues/32593

Then we can update the templates to use the new web workflow and set a proper lower constraint on the SDK.

**Comment by kevmoo** [comment]
Now we just need to wait for an SDK to get released w/ this change. Hoping it'll be `-dev.51`
