### ISSUE TITLE
Redirect/remove stagehand.pub site

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/stagehand#475]
The package page is easier...

**Comment by kevmoo** [comment]
http://stagehand.pub/ now redirects to https://github.com/dart-lang/stagehand

**Comment by kwalrath** [comment]
I thought we were going to redirect to https://pub.dartlang.org/packages/stagehand?

**Comment by kwalrath** [comment]
And yet... I approved something saying we'd redirect to github.

**Comment by kevmoo** [comment]
The last published package links to stagehand.pub – didn't want to put folks in a loop.

Will fix once we publish v2
