### ISSUE TITLE
Create 1.x and use master for 2.x

### ISSUE THREAD

**Issue by chalin** [dart-lang/stagehand#478]
We made this branch change over the site-www and site-webdev repos, maybe we should do that here too?

@kevmoo @kwalrath - WDYT?

cc @devoncarew

**Comment by devoncarew** [comment]
It would be nice to publish a `1.1.8` to capture the deps change for args. I'm not sure when the timing is for publishing the work from the 2.x branch, but moving that work to master sgtm.

**Comment by chalin** [comment]
Publishing of 1.1.8 first SGTM.

**Comment by kwalrath** [comment]
I'll publish 1.1.8 today.

**Comment by kevmoo** [comment]
1.1.9 was published. I moved v2 to master. Let's hold off creating a v1.x branch until we need to.
