### ISSUE TITLE
Is `enabled: true` still needed for the angular analyzer plugin?

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/stagehand#492]
https://github.com/dart-lang/stagehand/blob/5620319a42714d9b4beb206926080246401993f3/templates/web-angular/analysis_options.yaml#L7

@MichaelRFairhurst ?

**Comment by kevmoo** [comment]
@MichaelRFairhurst ?

**Comment by MichaelRFairhurst** [comment]
Nope! No longer required!

**Comment by kevmoo** [comment]
As of which release of the SDK?
