### ISSUE TITLE
Create CONTRIBUTING.md and add build instructions

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/stagehand#509]
In various places (https://github.com/dart-lang/stagehand/wiki/Updating-a-template's-version, https://github.com/dart-lang/stagehand/wiki/How-to-add-your-template-to-Stagehand, maybe more), we say that you should run `dart tool/grind.dart build`.

As of #507, you instead use `pub run build_runner build`.

@kevmoo has anything else changed that needs to be reflected in the wiki?

**Comment by kwalrath** [comment]
I'm good with having the docs in source, as long as it's clear (from the README or a wiki page or an obvious file/dirname) where to find those docs.

Maybe move the wiki pages to a top-level `doc` or `docs` directory like in the angular or sdk repos? I know `doc` is the name by pub package convention... not sure if we want to conform or not, since most/all of this doc will be aimed at implementers (not users) of the packages.

**Comment by kevmoo** [comment]
We could put it in
https://help.github.com/articles/setting-guidelines-for-repository-contributors/

**Comment by kwalrath** [comment]
CONTRIBUTING.md? Works for me.

**Comment by kevmoo** [comment]
Yup

**Comment by kwalrath** [comment]
Fixed in #553 and other PRs/commits.
