### ISSUE TITLE
Strange behaviour

### ISSUE THREAD

**Issue by dudochkin-victor** [dart-lang/stagehand#515]
Check the log bellow.
I just installed dart-sdk, and cant install stagehand on my linux computer. But with mac all Ok.
Can u help me with it?

blacksmith@dev ~/.pub-cache $ pub global activate stagehand
Resolving dependencies... (1.7s)
The current Dart SDK version is 2.0.0-dev.55.0.

Because stagehand <1.1.5 requires SDK version <2.0.0 and stagehand >=1.1.5 <1.1.7 depends on path ^1.3.0, stagehand <1.1.7 requires path ^1.3.0.
And because stagehand ^1.1.7 requires SDK version >=1.13.0 <2.0.0 and stagehand >=2.0.0 depends on path ^1.3.0, every version of stagehand requires path ^1.3.0.
So, because path >=0.6.6 requires SDK version >=0.6.6 <2.0.0 and pub global activate depends on stagehand any, version solving failed.

**Comment by dudochkin-victor** [comment]
close it. my fault. i was set PUB_ALLOW_PRERELEASE_SDK to false.

**Comment by kevmoo** [comment]
Ah! Glad you figured things out...
