### ISSUE TITLE
web-angular: reintroduce basic component tests based on pageloader 3

### ISSUE THREAD

**Issue by chalin** [dart-lang/stagehand#517]
The component tests were removed via:

- Angular: remove the dev-override on pageloader #487
- web-angular tests: drop use of page object class and pageloader mock #493

Related: https://github.com/dart-lang/site-webdev/issues/1351

**Comment by kevmoo** [comment]
Blocked by https://github.com/google/pageloader/issues/145

**Comment by kwalrath** [comment]
Not planned.
