### ISSUE TITLE
web-angular: first build yields 'delete files?' prompt

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/stagehand#526]
Because the generated file is included, but it wasn't built from the users machine.

Maybe we go back and *not* include the file and handle having a slightly ugly initial analysis?

Thoughts, @chalin ?

**Comment by chalin** [comment]
> slightly ugly initial analysis?

I think that folks will be more startled by having analysis errors out-of-the-box.

Shouldn't `--delete-conflicting-outputs` resolve this issue?

**Comment by alorenzen** [comment]
We should not be including generated files in the templates. That's setting the wrong precedence, and IMO might lead to even more confusion than some analysis errors out-of-the-box.

We should require an initial build.

**Comment by kevmoo** [comment]
This is better than having a build block from an IDE w/ the user having no
recourse...

**Comment by matanlurey** [comment]
What generated files are we checking in? AngularDart doesn't even support that

**Comment by kevmoo** [comment]
Generated files for pageloader...

**Comment by matanlurey** [comment]
Shouldn't we be using the same approach as AngularDart and using the cache folder?

**Comment by kevmoo** [comment]
This is getting into pkg:pageloader specifics – I have zero clue....

**Comment by alorenzen** [comment]
Pageloader uses pkg:build, just like angular, built_value, etc. There is no
reason to check it in to the repository, especially since we expect users
to make changes to their page objects and rerun the builder.

**Comment by chalin** [comment]
FYI, we discussed `cache` vs `source` in https://github.com/google/pageloader/issues/132.

**Comment by chalin** [comment]
We're including the generated files because of:
- https://github.com/google/pageloader/issues/145 _Consider `import` of generated PO files rather than use of `part` statements_

**Comment by chalin** [comment]
I.e., the problem is that if we don't include the generated files, then a project generated from the template will show errors in WebStorm right out-of-the-box. I'd really think that we should avoid that if we can.

**Comment by matanlurey** [comment]
I thought the resolution of https://github.com/google/pageloader/issues/145 was that it doesn't matter?

**Comment by chalin** [comment]
Oops, sorry @alorenzen, I hadn't seen your first comment here: https://github.com/dart-lang/stagehand/issues/526#issuecomment-394030068.

If we're all ok with build-errors out-of-the-box, then I can remove that generated file from the template, but I'll need to update the [Get Started](https://webdev-dartlang-org-dev.firebaseapp.com/guides/get-started) and [Setup](https://webdev-dartlang-org-dev.firebaseapp.com/angular/guide/setup) pages to add a build step in the WebStorm instructions.

**Comment by chalin** [comment]
> I thought the resolution of google/pageloader#145 was that it doesn't matter?

True, in the longer term. Short-term, I'm not sure.

I guess the main question is: _currently_, is there a way to have our cake and eat it too: I.e., be able to offer devs an out-of-the-box experience for a freshly generated project w/o any errors?

**Comment by kevmoo** [comment]
We could also pull pageloader support (again) until https://github.com/google/pageloader/issues/145 is fixed

That would let us get these other updates out, right?

**Comment by kevmoo** [comment]
Back to the future ? https://github.com/dart-lang/stagehand/pull/528

**Comment by chalin** [comment]
Here is a point in case (about having templates that generate an initial project free of errors) from @TimLavers on Gitter (the full quote is below, but the essence is the following): **Seemed sort of unintuitive, as if we needed to compile in order to have code that compiles**.

---

> Tim Lavers @TimLavers 20:23
Thanks @leonsenft I was really thrown by the $ and hadn't appreciated that there was an extra step involved - we write the page object, then run pub run build_runner build and then it compiles. Seemed sort of unintuitive, as if we needed to compile in order to have code that compiles. But I guess I've just learnt a bit more about code generation and the tool chain, so thanks for your help. It's compiling now and I'm sure that the rest will be straightforward (famous last words).

**Comment by alorenzen** [comment]
Is there any way for intellij to trigger an initial build after creating the project?

**Comment by kevmoo** [comment]
We'd have to coordinate w/ Jetbrains for that – wondering if 'pub get' is
run by default...

**Comment by chalin** [comment]
In WebStorm, the execution of `pub get` is under user control -- I'm not aware of it running automatically, although WS does warn if the `pubspec.yaml` file has changed.

(@kevmoo - maybe we should keep this issue open?)

**Comment by matanlurey** [comment]
I'm comfortable saying if the user needs to `pub get` to resolve build errors, running a single build is also reasonable. That being said, I don't understand why the default user scaffold for `web-angular` needs a `pageloader`-based test. That's pretty advanced stuff for the external community, no?

**Comment by chalin** [comment]
The goal was to illustrate a basis for writing component tests, and it doesn't take long before one needs to write POs.

**Comment by TimLavers** [comment]
The page loader test examples are really great. This kind of thing is
needed in bridging the gap between examples like the (excellent) Tour of
Heroes example and getting a well engineered system running. By way of
comparison, Page Object style testing is introduced pretty early on in the
Flutter documentation, as I recall.

**Comment by matanlurey** [comment]
> The page loader test examples are really great.

Sure. Huge 👍 to having these examples, I'm not sure they need to be in the template.

**Comment by chalin** [comment]
@filiph likes to have rich templates (and was behind the idea of, for example, including use of angular_components, in the template) so he might have some thoughts to share.

IMHO, providing a base example of the use of pageloader page objects is a good idea. But I understand that we might not be able to do so because of current tooling(?) limitations.

**Comment by jakemac53** [comment]
We could add a global configuration section to the `build.yaml` which would essentially include support for changing the defaults of all the available command line flags.

This would enable you to set `delete_conflicting_outputs: true` in a `build.yaml` that is included with the template?

**Comment by matanlurey** [comment]
> @filiph likes to have rich templates (and was behind the idea of, for example, including use of angular_components, in the template) so he might have some thoughts to share.

Sure that makes sense, and is totally orthogonal to supplying page objects in the scaffold.

> IMHO, providing a base example of the use of pageloader page objects is a good idea. But I understand that we might not be able to do so because of current tooling(?) limitations.

Again, definitely a good idea. I don't know if it needs to be in the `web-angular` template. My guess is 95-99% of users will not use it, and it will just be confusing to them. I'd rather we have a dedicated testing page/guide/scaffold.
