### ISSUE TITLE
Bound SDK for web-angular until next release +15 of angular et all

### ISSUE THREAD

**Issue by chalin** [dart-lang/stagehand#533]
Version +14 of angular should be used with SDK no greater than 2-dev.61. Folks are repeatedly hitting this problem as they upgrade their SDK:

- https://github.com/dart-lang/angular/issues/1406
- https://github.com/dart-lang/angular/issues/1411
- https://github.com/dart-lang/angular/issues/1412

cc @kwalrath @kevmoo

**Comment by kevmoo** [comment]
Is -dev.63 okay, though? We should just get a version out that support it...right?

**Comment by matanlurey** [comment]
We released +15 today

**Comment by chalin** [comment]
> Is -dev.63 okay, though? We should just get a version out that support it...right?

If we want to move beyond SDK 2-dev.61, we need to use Angular +15.
But ACX +15 isn't out yet.
ACX +14 seems to be usable with NG +15, so if you are ok with a dep override, I can go that route.

**Comment by chalin** [comment]
Anyhow, given that NG +15 is out I'll close this.
