### ISSUE TITLE
https://github.com/dart-lang/stagehand/releases/latest doesn't point to latest release

### ISSUE THREAD

**Issue by chalin** [dart-lang/stagehand#537]
https://github.com/dart-lang/stagehand/releases/latest currently redirects to v2.0.1. Should it not redirect to the latest 3.x release?

**Comment by kwalrath** [comment]
It looks like whoever did those releases didn't tag them... I'll do that.

**Comment by kwalrath** [comment]
Wait, they are tagged. Maybe it's because they have no release notes? I'll try adding those.

**Comment by chalin** [comment]
That seems to have done it.

**Comment by kwalrath** [comment]
Ah, they were tagged but had nothing in the release title field. I added that and (while I was there) release notes.
