### ISSUE TITLE
web-angular: remove temporary dependency override

### ISSUE THREAD

**Issue by chalin** [dart-lang/stagehand#538]
https://github.com/dart-lang/stagehand/blob/4e54ee0f293852d743233d9df90fa0cf9944ee07/templates/web-angular/pubspec.yaml#L21-L23

**Comment by kevmoo** [comment]
Is this all that's blocking us from `3.1.0`?

**Comment by chalin** [comment]
Yes (for 3.0.1).

**Comment by chalin** [comment]
@kevmoo - should 3.0.1 be published now? /cc @kwalrath

**Comment by kevmoo** [comment]
I think so!
