### ISSUE TITLE
stagehand 3.0.0 defaults to snapshot 1.1 not 2

### ISSUE THREAD

**Issue by isoos** [dart-lang/stagehand#544]
_From @CarnivalRaid on June 25, 2018 8:47_

URL: https://pub.dartlang.org/packages/stagehand#-versions-tab-

When dart2 dev sdk is installed, executing stagehand web-angular should use snapshot dart2.

Hello there. I have installed dart 2 64.1-1 and wanted to try angular 5. After doing a:
 "pub global activate stagehand" and "pub global activate webdev", i have errors on stagehand and webdev. I saw that errors appear because the script uses snapshots 1.1 from either two.
The error on stagehand web-angular command is: "..../.pub-cache/global_packages/stagehand/bin/stagehand.dart.snapshot:1:1: Error: Unable to decode bytes as UTF-8.
���ܶj "
The error in webdev is a bit more complicated for me to understand and way longer.
If I do manualy dart and pick the snapshots from bin that are ended with dart2 it works as expected.
I installed as indicated on the website in preview angular 5, dart2 sdk (dev).
OS: WattOS (it's a stripdown  version of Ubuntu 16.04.4 LTS -Xenial).

I want to appologise in advance. I am new to programming, github and reporting issues.(but i love what you are doing with dart and angular and flutter)
Great day, devs.

_Copied from original issue: dart-lang/pub-dartlang-dart#1408_

**Comment by CarnivalRaid** [comment]
Szia :) and thanks.

**Comment by chalin** [comment]
There is a [problem with `pub`](https://github.com/dart-lang/pub/issues/1932). As mentioned here https://github.com/dart-lang/stagehand/issues/543#issuecomment-399668142, can you instead try running:

```console
> pub global run stagehand web-angular
```

**Comment by CarnivalRaid** [comment]
Hello @chalin, thanks for the fast reply. It works as expected with that command.
I also did a:
>pub global run webdev serve and works well too. For those who have these problems.

Thank you.

**Comment by CarnivalRaid** [comment]
@kevmoo Hello there. I have upgraded to -dev.65. It is working great, both stagehand and webdev.
Thank you, and a great day.

**Comment by chalin** [comment]
Great! Closing.
