### ISSUE TITLE
Roll stagehand pkg:angular version to beta

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/stagehand#547]
**blocked** on publishing angular beta

**Comment by chalin** [comment]
SGTM!

**Comment by chalin** [comment]
@kevmoo - will we be setting the min SDK to 2-dev.65 (or .66 if it is out)?

**Comment by kevmoo** [comment]
.65 is good

**Comment by chalin** [comment]
I suppose that we'll be waiting for the ACX beta release too, right? /cc @kwalrath

**Comment by kevmoo** [comment]
Yup!
