### ISSUE TITLE
Eliminate redundant imports from angular_components

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/stagehand#550]
https://github.com/dart-lang/stagehand/blob/41d5efaf36802aba33daf093382e1d650d341ea5/templates/web-angular/lib/src/todo_list/todo_list_component.dart#L4-L9

Removing the individual component imports doesn't affect build success.

Can we just stick w/ the one import? What's best practices?

@nshahan @chalin @kwalrath

**Comment by kwalrath** [comment]
According to https://github.com/dart-lang/stagehand/issues/496#issuecomment-384718252:

> If you want the best build times and smallest possible output from dart2js then you should only import what you are using. Even the best tree shaking can't prove that are are not going to use some code when we are dealing with hash tables with dynamic types etc.

**Comment by kwalrath** [comment]
Oops... but yes, we shouldn't be importing angular_components.dart.

**Comment by matanlurey** [comment]
> If you want the best build times and smallest possible output from dart2js then you should only import what you are using. Even the best tree shaking can't prove that are are not going to use some code when we are dealing with hash tables with dynamic types etc.

This statement is not true, btw. Imports have 0 effect on Dart2JS. That might have been true at some point. It _does_ have an effect on `build_runner`, but lets just make clear that it is not effecting tree shaking (well, it can, but not with `runApp()`).

**Comment by kevmoo** [comment]
@matanlurey – should we tell folks to use `runApp`? Or something else?

**Comment by matanlurey** [comment]
We do tell them in our CHANGELOG and migration guide and a few other places.

**Comment by kevmoo** [comment]
Is this template "doing it right"?

**Comment by matanlurey** [comment]
Looks like it: https://github.com/dart-lang/stagehand/blob/41d5efaf36802aba33daf093382e1d650d341ea5/templates/web-angular/web/main.dart#L5

**Comment by nshahan** [comment]
> This statement is not true, btw. Imports have 0 effect on Dart2JS. That might have been true at some point. It does have an effect on build_runner, but lets just make clear that it is not effecting tree shaking (well, it can, but not with runApp()).

I tried with the stagehand template and found that the size of the output `main.dart.js` file did increase when using the mono import from 275kb --> 382kb

This was building with `pub run build_runner build --release`.

Mono Import: https://github.com/nshahan/components-size-test
Individual Imports: https://github.com/nshahan/components-size-test/tree/individual-imports

**Comment by matanlurey** [comment]
To be clear, I mean the `import` statements themselves should have no effect.

The effect of:

```dart
    MaterialCheckboxComponent,
    MaterialFabComponent,
    MaterialIconComponent,
    MaterialInputComponent,
    MaterialInputDefaultValueAccessor,
    MaterialInputBlurValueAccessor,
    MaterialInputChangeValueAccessor,
```

versus `materialDirectives`, might (more directives might be matching, for example). It is one of the reason I really don't like Lists of components or directives. I imagine if we ever write AngularDart specific lints this is one of the scenarios we'd try to prevent as a best practice.

**Comment by kwalrath** [comment]
So... The current version of the stagehand template is mostly doing the right thing, it seems like, except maybe for [MaterialInputDirectives](https://webdev.dartlang.org/api/angular_components/angular_components/materialInputDirectives-constant): 

https://github.com/dart-lang/stagehand/blob/3744f3968ae6f5fd646461a9e79c9b5729d34ac5/templates/web-angular/lib/src/todo_list/todo_list_component.dart#L3-L19

How much does it cost to use MaterialInputDirectives?

**Comment by nshahan** [comment]
> To be clear, I mean the import statements themselves should have no effect.

Great point. I have conflated the two in my mind as the "convenient" way of using the components. The single import with all the individual directives listed out compiles to the exact same size as the multiple imports. Sorry about my confusion there.

**Comment by matanlurey** [comment]
No worries, I got confused myself!

**Comment by nshahan** [comment]
I'm pretty sure you need the NgModel, and the with an angular_forms import or else you wont be able to capture the value from the input when you add the todo item.
