### ISSUE TITLE
pub still giving errors: 2.0.0-dev.67.0

### ISSUE THREAD

**Issue by biancashouse** [dart-lang/stagehand#554]
from a previous issue about pub, I managed to get a sample project created using"

    pub global run stagehand web-angular

SO before I can run the app, I need to:

    pub get

This gives me lots of instances of the following message:

    Error: NoSuchMethodError: Class 'BuildStepImpl' has no instance method 'digest'.
    Receiver: Instance of 'BuildStepImpl'
    Tried calling: digest(Instance of 'AssetId')
    [BuilderTransformer: Instance of 'SassBuilder' on angular_components|primary]:

**Comment by biancashouse** [comment]
Hi Patrice, thanks for the respone. I find that installing dart 2 does not
actually include pub. So I assume I was using the pub that comes with dart
1. So do I need to install dart 1 followed by dart 2 ?

1. unistalled dart (sudo apt remove dart)
2. installed dart (dart --version -> Dart VM version: 2.0.0-dev.67.0
(Unknown timestamp) on "linux_x64"Dart VM version: 2.0.0-dev.67.0 (Unknown
timestamp) on "linux_x64"
3. when I run pub, it's not found !

Since I'm new to Dart (been using GWT for years), I thought it would make
sense to start with Dart 2, particularly since I'm planning to use
Flutter...

Cheers

Ian

**Comment by biancashouse** [comment]
Doh, dart sdk was hiding in /usr/lib/dart.

Many thanks.

**Comment by biancashouse** [comment]
Found that the dart-sdk is installed in /usr/lib/dart.
I was looking under /usr/local !

So in my profile I do:

export DATK_SDK_HOME=/usr/lib/dart
export PATH=$PATH......:$DART_SDK_HOME/bin

Now pub works as documented. Phew.

**Comment by chalin** [comment]
I'm glad it all worked out!
