### ISSUE TITLE
Improve Maintenance score

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/stagehand#555]
Our Maintenance score has dropped to 72 (used to be 100?).

https://pub.dartlang.org/packages/stagehand#-analysis-tab-
https://pub.dartlang.org/help#maintenance

**Comment by chalin** [comment]
It seems that an earlier SDK (2-dev.63) is running on the pub server and causing errors:

> <img width="613" alt="screen shot 2018-07-09 at 17 57 03" src="https://user-images.githubusercontent.com/4140793/42478133-95cce4f4-83a1-11e8-80d1-d1d31643977e.png">

**Comment by kwalrath** [comment]
Closing because the score is bogus until pub updates to a more recent version of Dart.
