### ISSUE TITLE
Comment out analyzer plugin – with note about how to enable

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/stagehand#561]
i.e. remove https://github.com/dart-lang/stagehand/blob/e810f641151f733251a5f036ab8d789f930145d4/templates/web-angular/analysis_options.yaml#L5-L6.

This is one of the top issues filed and mentioned externally (i.e. bugs in the plugin).

**Comment by kevmoo** [comment]
Just talked to @MichaelRFairhurst . We think we should drop this for gold.

Maybe comment it out and put in a comment saying support is beta. Try at your own risk. Please file issues?

**Comment by matanlurey** [comment]
Ok. Totally supportive of the comment!

**Comment by kwalrath** [comment]
OK, I'll make this happen.

**Comment by kevmoo** [comment]
@chalin – can you run w/ this?

**Comment by kwalrath** [comment]
I'm about to release stagehand now.

**Comment by kevmoo** [comment]
Ack!
