### ISSUE TITLE
Failed to recompile stagehand:stagehand

### ISSUE THREAD

**Issue by deaitch** [dart-lang/stagehand#572]
Hi I 'repaired cache' in webstorm after getting an error in a generated test file out of the blue but got the following error:

Reinstalled 359 packages.
Reactivating stagehand 2.0.2...
Precompiling executables...
Failed to precompile stagehand:stagehand:
file:///Users/john/.pub-cache/hosted/pub.dartlang.org/http-0.11.3+16/lib/src/byte_stream.dart:31:51: Error: Getter not found: 'UTF8'.
  Future<String> bytesToString([Encoding encoding=UTF8]) =>
                                                  ^^^^
file:///Users/john/.pub-cache/hosted/pub.dartlang.org/http-0.11.3+16/lib/src/byte_stream.dart:31:51: Error: The getter 'UTF8' isn't defined for the class '#lib1::ByteStream'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'UTF8'.
  Future<String> bytesToString([Encoding encoding=UTF8]) =>

My pubspec.yaml:
name: angular_tour_of_heroes
description: Tour of Heroes
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev.69.5 <3.0.0'

dependencies:
  angular: ^5.0.0-beta
  angular_forms: ^2.0.0-beta
  angular_components: ^0.9.0
  firebase: ^5.0.0

dev_dependencies:
  angular_test: ^2.0.0-beta
  build_runner: ^0.9.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  pageloader: ^3.0.0-beta
  sass_builder: ^2.0.2
  test: ^1.0.0

Running on:
Dart VM version: 2.0.0-dev.69.5 (Tue Jul 31 15:05:14 2018 +0200) on "macos_x64"

**Comment by deaitch** [comment]
For completeness the original error I started getting was:
Please check the following imports:

`import 'package:angular_tour_of_heroes/app_component.template.dart' as ng;` from angular_tour_of_heroes|web/main.dart at 2:1


[SEVERE] build_web_compilers|entrypoint on test/app_test.dart.browser_test.dart (cached):
Unable to find modules for some sources, this is usually the result of either a
bad import, a missing dependency in a package (or possibly a dev_dependency
needs to move to a real dependency), or a build failure (if importing a
generated file).

Not sure if there would be a connection or not...

**Comment by chalin** [comment]
Thanks for filing an issue. Can you upgrade to Dart 2.0.0 and try again?

**Comment by deaitch** [comment]
Hi @chalin I can confirm having done the following to upgrade to Dart 2.0.0 I no longer get this error... thanks very much for your help

//unliks dev SDK
brew unlink dart
// installs latest stable
brew install dart
as outlined here:
https://webdev.dartlang.org/tools/sdk

**Comment by chalin** [comment]
I'm glad that did it.
