### ISSUE TITLE
'webdev serve' fails on web-angular boiler

### ISSUE THREAD

**Issue by exo-pla-net** [dart-lang/stagehand#574]
Running Dart version: 2.0.0.

> webdev could not run for this project.
> The `build_runner` version – 0.10.1+1 – is not within the allowed constraint – >=0.8.10 <0.10.0.

**Comment by chalin** [comment]
Thanks for the issue. A few questions:

- Which version of stagehand are you using?
- Are you using the latest webdev version? Try re-running `pub global activate webdev`

I just tried with the stagehand from this repo, and webdev 0.2.4 and it runs fine.

**Comment by exo-pla-net** [comment]
Needed to update webdev; works fine now. Thanks!

**Comment by kwalrath** [comment]
I'm going to edit https://webdev.dartlang.org/tools/webdev to make clear how to update webdev.
