### ISSUE TITLE
templates: add web-angular-simple template

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/stagehand#575]
Align with the "Tour of Heroes" quickstart - https://github.com/angular-examples/quickstart

**Comment by chalin** [comment]
Revert PR #403, which was addressing the original issue of #390? /cc @kwalrath @devoncarew

**Comment by kwalrath** [comment]
I should talk with Kevin about this. Maybe tomorrow morning, @kevmoo?

**Comment by kwalrath** [comment]
Not planned.
