### ISSUE TITLE
Exhausted heap space, trying to allocate 12648 bytes.

### ISSUE THREAD

**Issue by meflyup** [dart-lang/stagehand#581]
when execute command like 
```
stagehand web-simple    or
stagehand web-angular
```
it shows:
```
Exhausted heap space, trying to allocate 12648 bytes.
```

Thanks!

**Comment by meflyup** [comment]
Sorry, It's ok now ,I think it is because i have two stagehand installed.

**Comment by kwalrath** [comment]
That's very strange! Thanks for letting us know what happened.
