### ISSUE TITLE
consider updating template to use `package:pedantic` lints

### ISSUE THREAD

**Issue by pq** [dart-lang/stagehand#593]
The current [list of lints](https://github.com/dart-lang/stagehand/blob/master/templates/analysis_options.yaml) is its own subset of the [complete list](https://github.com/dart-lang/linter/blob/master/example/all.yaml).  Historically this has been hand-edited, with the `pana` package [manually updated](https://github.com/dart-lang/pana/blob/master/lib/src/analysis_options.dart) to keep consistent.  Before we had a set of "standard" defaults this made sense but now that we have the evolving set of Google standard lints defined by [`package:pedantic`](https://github.com/dart-lang/pedantic) we should consider updating the template to use those.

@kevmoo @devoncarew  @mit-mit: any reason _not_ to prefer the `pedantic` rules for sample projects?

/cc @davidmorgan @bwilkerson

**Comment by kevmoo** [comment]
I'm a fan of pedantic here – at least investigate it

**Comment by pq** [comment]
There's a kind of meta conversation unfurling in https://github.com/dart-lang/linter/issues/1365.  Feel free to chime in!
