### ISSUE TITLE
stagehand 3.3.0 doesn't support Dart 2.1.2-dev

### ISSUE THREAD

**Issue by clowdydaze** [dart-lang/stagehand#609]
Trying to build a flutter web project and that's the message under VSCode after selecting <Flutter:New Web Project> in Command Palette.

I initially tried to run it with existing stagehand and was messaged to upgrade to 3.3.0.

Which version of Dart must I have?

Full Error:

[flutter-web-preview] pub global run stagehand flutter-web-preview
stagehand 3.3.0 doesn't support Dart 2.1.2-dev.0.0.flutter-0a7dcf17eb.
exit code 65

**Comment by kevmoo** [comment]
Please upgrade to the latest flutter stable release - 1.5 – and you should be good!
https://medium.com/flutter-io/announcing-flutter-1-5-d203c6072e5c

**Comment by clowdydaze** [comment]
yep!
