### ISSUE TITLE
Integrate into pub

### ISSUE THREAD

**Issue by shyndman** [dart-lang/stagehand#610]
Introducing a `pub new` or `pub init` backed by a project scaffolder like Stagehand is important to encouraging an experimental attitude towards creating Dart packages. 

I know with that node, `npm init` along with yeoman are my gotos for creating quick one off script projects. Moments ago, I found myself in that position with Dart. I reached for that ability, didn't find it, and felt the barrier to entry. Worth considering.

**Comment by kwalrath** [comment]
This issue would belong on https://github.com/dart-lang/pub, and you're welcome to file it there, but the tendency has been for pub to do less, not more.

E.g. see https://github.com/dart-lang/pub/issues/1847.

**Comment by 89z** [comment]
https://github.com/dart-lang/pub/issues/2938

**Comment by 89z** [comment]
https://github.com/dart-lang/pub/issues/1847
https://github.com/dart-lang/pub/issues/2938
https://github.com/dart-lang/sdk/issues/35364

https://github.com/dart-lang/stagehand/issues/610
