### ISSUE TITLE
'pub get' version solving fails from fresh 'package-simple' and 'console-full'

### ISSUE THREAD

**Issue by ViciousVisions** [dart-lang/stagehand#616]
The versions of the stagehand included test packages are incompatible.

>> dart --version
Dart VM version: 2.4.0 (Wed Jun 19 11:53:45 2019 +0200) on "windows_x64"

==========
= console-full =
==========
>> stagehand console-full
Creating console-full application `args`:
  B:\code\dart\training\command_line\args\.gitignore
  B:\code\dart\training\command_line\args\CHANGELOG.md
  B:\code\dart\training\command_line\args\README.md
  B:\code\dart\training\command_line\args\analysis_options.yaml
  B:\code\dart\training\command_line\args\bin/main.dart
  B:\code\dart\training\command_line\args\lib/args.dart
  B:\code\dart\training\command_line\args\pubspec.yaml
  B:\code\dart\training\command_line\args\test/args_test.dart
8 files written.

--> to provision required packages, run 'pub get'
--> run your app using `dart bin/main.dart`.

>>pub get
Resolving dependencies...
Because test >=1.5.0 <1.5.1 depends on test_core 0.1.0 and test >=1.5.1 <=1.5.1 depends on test_core 0.2.0, test
  >=1.5.0 <=1.5.1 requires test_core 0.1.0 or 0.2.0.
And because test >=1.5.1+1 <1.5.2 depends on test_core 0.2.0+1, test >=1.5.0 <1.5.2 requires test_core 0.1.0 or 0.2.0
  or 0.2.0+1.
And because test >=1.5.2 <1.5.3 depends on test_core 0.2.1 and test >=1.5.3 <1.6.0 depends on test_core 0.2.1+1, test
  >=1.5.0 <1.6.0 requires test_core 0.1.0 or 0.2.0 or 0.2.0+1 or 0.2.1 or 0.2.1+1.
And because test >=1.6.0 <1.6.1 depends on test_core 0.2.2 and test >=1.6.1 <1.6.2 depends on test_core 0.2.3, test
  >=1.5.0 <1.6.2 requires test_core 0.1.0 or 0.2.0 or 0.2.0+1 or 0.2.1 or 0.2.1+1 or 0.2.2 or 0.2.3.
And because test >=1.6.2 <1.6.3 depends on test_core 0.2.4 and test >=1.6.3 <1.6.4 depends on test_core 0.2.5, test
  >=1.5.0 <1.6.4 requires test_core 0.1.0 or 0.2.0 or 0.2.0+1 or 0.2.1 or 0.2.1+1 or 0.2.2 or 0.2.3 or 0.2.4 or 0.2.5.
And because test >=1.6.4 depends on test_core 0.2.6 which depends on args ^1.4.0, test >=1.5.0 requires args ^1.4.0.
So, because args depends on test ^1.5.0 and args is 0.0.0, version solving failed.

=============
= package-simple =
=============
>> stagehand package-simple
Creating package-simple application `args`:
  B:\code\dart\training\command_line\args\.gitignore
  B:\code\dart\training\command_line\args\CHANGELOG.md
  B:\code\dart\training\command_line\args\README.md
  B:\code\dart\training\command_line\args\analysis_options.yaml
  B:\code\dart\training\command_line\args\example/args_example.dart
  B:\code\dart\training\command_line\args\lib/args.dart
  B:\code\dart\training\command_line\args\lib/src/args_base.dart
  B:\code\dart\training\command_line\args\pubspec.yaml
  B:\code\dart\training\command_line\args\test/args_test.dart
9 files written.

--> to provision required packages, run 'pub get'
>> pub get
Resolving dependencies...
Because test >=1.6.0 <1.6.1 depends on test_core 0.2.2 and test >=1.6.1 <1.6.2 depends on test_core 0.2.3, test
  >=1.6.0 <1.6.2 requires test_core 0.2.2 or 0.2.3.
And because test >=1.6.2 <1.6.3 depends on test_core 0.2.4 and test >=1.6.3 <1.6.4 depends on test_core 0.2.5, test
  >=1.6.0 <1.6.4 requires test_core 0.2.2 or 0.2.3 or 0.2.4 or 0.2.5.
And because test >=1.6.4 depends on test_core 0.2.6 which depends on args ^1.4.0, test >=1.6.0 requires args ^1.4.0.
So, because args depends on test ^1.6.0 and args is 0.0.0, version solving failed.

**Comment by ViciousVisions** [comment]
pub --version
Pub 2.4.0

stagehand --version
stagehand version: 3.3.2

**Comment by ViciousVisions** [comment]
Resolved.
Problem: home directory name (args) was the same as the package name (args) and caused a conflict.
Fix: Changed home directory name.

**Comment by KannanPalani57** [comment]
thanks , it helped me.
