### ISSUE TITLE
build doesn't work on windows

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/stagehand#627]
See #626 for details.

We should at least update the contributor's guide accordingly. Another possibility is to make the build work on windows; I don't know how hard that would be.

**Comment by Fox32** [comment]
In general, the build of the template could work, if we force the repository line breaks on all systems. This can be done via a `.gitattributes` file, like:
```
* -text
```
This has the downside that some Windows editors don't understand the line endings, but everyone should use an editor that supports that by now...

What doesn't work and should be part of the contributor's guide is, that `dart test/validate_templates.dart` doesn't work on Windows, as the generated code uses the operating system line breaks and do not match the expected line breaks.

I can send a PR if you agree with this.
