### ISSUE TITLE
Update/delete Flutter template

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/stagehand#632]
To reflect https://github.com/flutter/flutter/wiki/Upgrading-from-package:flutter_web-to-the-Flutter-SDK

**Comment by kwalrath** [comment]
Or should we delete it?

@johnpryan, @yjbanov

**Comment by johnpryan** [comment]
We can delete it - the samples generated from `flutter create` work without any additional setup.

**Comment by kwalrath** [comment]
@domesticmouse are you able to do this, or shall I?
