### ISSUE TITLE
add a 'console-simple' template

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/stagehand#650]
Are current templates are:

```
console-full - A command-line application sample.
package-simple - A starting point for Dart libraries or applications.
server-shelf - A web server built using the shelf package.
web-angular - A web app with material design components.
web-simple - A web app that uses only core Dart libraries.
web-stagexl - A starting point for 2D animation and games.
```

There was recent discussion about adding a `console-simple` template. This might be something as simple as:

- `pubspec.yaml`
- `bin/main.dart`
- `.gitignore`

Here's the `console-full` template in comparison: https://github.com/dart-lang/stagehand/tree/master/templates/console-full. It contains a lib/ file, a test/ file, and a few more general project files in the main project directory.

Thoughts on what subset of files `console-simple` might have? Thoughts on deleting `console-full`? Or, reducing the number of files in `console-full` and renaming to `console-simple`?

cc @kwalrath @jwren @kevmoo @mit-mit

**Comment by kevmoo** [comment]
SGTM

**Comment by kwalrath** [comment]
I like the idea of a dirt-simple console template to help people play with the language. It seems like console-full might still be useful for people doing real command-line tools. So console-simple + console-full SGTM.
