### ISSUE TITLE
Can't upgrade to 3.3.9

### ISSUE THREAD

**Issue by JSeppl** [dart-lang/stagehand#674]
Newly activating stagehand not updates to latest version.

Package stagehand is currently active at version 3.3.7.
Resolving dependencies...
+ stagehand 3.3.7 (3.3.9 available)
Precompiling executables...
Precompiled stagehand:bin\stagehand.
Installed executable stagehand.
Activated stagehand 3.3.7.

**Comment by JSeppl** [comment]
Think this must be moved to pub.

**Comment by kwalrath** [comment]
I wonder if it's related to your SDK version. Stagehand uses 2.8.1+.
