### ISSUE TITLE
Could not find a file named "pubspec.yaml" in example folder

### ISSUE THREAD

**Issue by aliyazdi75** [dart-lang/stagehand#685]
If I added `flutter` to my dependencies, it would say:
`Could not find a file named "pubspec.yaml" in example folder` for `pub get`.
But I really don't wanna use `pubspec.yaml` in the example directory.

**Comment by kwalrath** [comment]
I believe that `pub get` needs to run in the same directory as the `pubspec.yaml` file, so you'll need to go up a level and then run it.

**Comment by aliyazdi75** [comment]
I know this thing :)
I did that but it says that thing since I added flutter.
The packages don't have flutter as their dependency `pub get` works fine.

**Comment by aliyazdi75** [comment]
Btw I'm using `flutter pub get`
Is that cause the problem?

**Comment by kwalrath** [comment]
You've reached the limit of my knowledge :). Try StackOverflow?

**Comment by kwalrath** [comment]
Closing as not a stagehand issue.

**Comment by aliyazdi75** [comment]
@kwalrath 
Maybe stagehand can build a `pubspec.yaml` for the example folder?

**Comment by aliyazdi75** [comment]
@kwalrath 
As this https://github.com/dart-lang/pub/issues/2831 says, it must have at least an empty `pubspec.yaml` inside the `example` folder.

**Comment by kwalrath** [comment]
@domesticmouse what do you think?

**Comment by domesticmouse** [comment]
I'm confused on what this bug is about. I'm guessing the example library projects that `stagehand` produces contain an empty example directory?

I think it would be good to have an example `pubspec.yaml` that references the enclosing project, otherwise new users may be confused as to why the example can't use code defined in the surounding codebase...

**Comment by aliyazdi75** [comment]
@domesticmouse 
The folder tree looks like this with no `pubspec.yaml` inside the `example` directory:
```
├── analysis_options.yaml
├── example
│   └── pkg1_example.dart
├── lib
│   ├── pkg1.dart
│   └── src
├── pubspec.lock
├── pubspec.yaml
├── README.md
└── test
    └── pkg1_test.dart
```

**Comment by domesticmouse** [comment]
Yeah, that's broken. 

@kwalrath feel free to assign this to me. 

/cc @kevmoo

**Comment by kevmoo** [comment]
It's not required to have a pubspec in `example/` – seems like a Flutter issue

**Comment by aliyazdi75** [comment]
The flutter issue is here https://github.com/flutter/flutter/issues/74234

**Comment by domesticmouse** [comment]
I believe we should close this out as the issue is being dealt with in the flutter/flutter tracker.

**Comment by aliyazdi75** [comment]
I'm so confused. I don't understand whether it is necessary to have `pubspec.yaml` or not? If not, why they told me it is?

**Comment by domesticmouse** [comment]
What told you that you need a `pubspec.yaml` in your example directory?

It helps to have a full reproduction case when posting an issue =)

**Comment by aliyazdi75** [comment]
> @kwalrath
> As this [dart-lang/pub#2831](https://github.com/dart-lang/pub/issues/2831) says, it must have at least an empty `pubspec.yaml` inside the `example` folder.

@domesticmouse 
This is where I mentioned.

**Comment by domesticmouse** [comment]
@aliyazdi75 my reading of that bug is that @jonasfj is considering adding this as an enhancement. I'm guessing this would only be for example directories that contain a pubspec.yaml as this hasn't been a requirement for Dart packages up until now.

**Comment by aliyazdi75** [comment]
@domesticmouse 
I see. So `pub get` doesn't make this issue then? and this should be fixed in `flutter pub get`
Thanks for the replies.

**Comment by aliyazdi75** [comment]
@domesticmouse 
I think someone fixed this problem with the new flutter updates :smile:
