### ISSUE TITLE
pub: command not found

### ISSUE THREAD

**Issue by nailuj29gaming** [dart-lang/stagehand#695]
I just updated my flutter SDK (which includes Dart) and I'm now running into this error when I try to run Stagehand: 
```
/home/nailuj29/.pub-cache/bin/stagehand: 7: pub: not found
```

**Comment by domesticmouse** [comment]
You'll want to re-activate `stagehand` to update it:

```bash
$ dart pub global deactivate stagehand
$ dart pub global activate stagehand
```

**Comment by nailuj29gaming** [comment]
That fixed my problem, thank you
